
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
﻿name: License Eye
on:
  pull_request:

jobs:
  license:
    permissions: write-all
    uses: RokctAI/shared-workflows/.github/workflows/universal-license.yml@main
    secrets: inherit


