name: Code Quality
# Copy to: .github/workflows/linters.yml

on: [push, pull_request]

jobs:
  lint:
    uses: RokctAI/shared-workflows/.github/workflows/universal-linter.yml@main
    secrets: inherit
