# Hadolint configuration
ignored:
  - DL3008 # Pin versions in apt get install
  - DL3018 # Pin versions in apk add
  - DL3015 # Avoid additional packages
  - DL3009 # Clean apt-get cache
  - DL3006 # Always tag image
  - DL3047 # wget non-verbose
