#!/usr/bin/env python3
# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Tests for scripts/pr_footer_cleanup.py (the universal-semantic footer-cleanup job).

Pins the exact footer shapes the fleet receives on pull requests, that the
stripping is idempotent, and that nothing else in a PR body is touched -
the `- [ ]` checklist lines in particular, because `checklist-check` reads
the cleaned body straight after this job.

Run:  python3 scripts/tests/test_pr_footer_cleanup.py
      python3 -m unittest discover -s scripts/tests    (also works)
"""

import importlib.util
import os
import subprocess
import sys
import unittest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SCRIPT = os.path.join(REPO_ROOT, "scripts", "pr_footer_cleanup.py")

_spec = importlib.util.spec_from_file_location("pr_footer_cleanup", SCRIPT)
cleanup = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(cleanup)

strip = cleanup.strip_attribution

FOOTER = (
    "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"
    "\n"
    "https://claude.ai/code/session_014LsFCCxNmhtmHYQBBLhbMt"
)
DOUBLED_FOOTER = (
    FOOTER + "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
)

BODY = (
    "## Description\n"
    "Adds the thing.\n"
    "\n"
    "## Type of change\n"
    "- [x] **feat** – new feature\n"
    "\n"
    "## Checklist\n"
    "- [ ] Version bump in `pubspec.yaml`\n"
    "- [x] All tests pass\n"
    "\n"
    "See [the docs](https://example.com/docs) and `---` in code.\n"
    "\n"
    "---\n"
    "\n"
    "A section after a real horizontal rule."
)


class ExactFooterShapes(unittest.TestCase):
    def test_my_exact_footer_at_end(self):
        self.assertEqual(strip("Adds X.\n\n" + FOOTER), "Adds X.")

    def test_doubled_variant_with_rule_and_generated_by(self):
        self.assertEqual(strip("Adds X.\n\n" + DOUBLED_FOOTER), "Adds X.")

    def test_plain_text_forms_and_case(self):
        self.assertEqual(strip("Adds X.\n\n🤖 generated with claude code\n"), "Adds X.")
        self.assertEqual(strip("Adds X.\n\nGenerated by Claude Code"), "Adds X.")
        self.assertEqual(strip("Adds X.\n\n*Generated by Claude Code*"), "Adds X.")

    def test_session_line_variants(self):
        for line in (
            "https://claude.ai/code/session_abc-DEF_123",
            "<https://claude.ai/code/session_abc>",
            "[session](https://claude.ai/code/session_abc)",
            "Session: https://claude.ai/code/session_abc",
        ):
            with self.subTest(line=line):
                self.assertEqual(strip("Adds X.\n\n" + line), "Adds X.")

    def test_crlf_bodies_keep_crlf(self):
        body = "Adds X.\r\n\r\nMore.\r\n\r\n" + FOOTER.replace("\n", "\r\n")
        self.assertEqual(strip(body), "Adds X.\r\n\r\nMore.")


class NothingElseIsTouched(unittest.TestCase):
    def test_body_without_footer_is_returned_as_is(self):
        self.assertIs(strip(BODY), BODY)
        self.assertIs(strip(""), "")
        self.assertIs(strip(None), None)

    def test_checkboxes_headings_links_and_real_rules_survive(self):
        self.assertEqual(strip(BODY + "\n\n" + DOUBLED_FOOTER), BODY)

    def test_footer_mid_text_removes_only_the_block(self):
        body = "Intro\n\n" + FOOTER + "\n\n## Next\n- [ ] item\n- [x] done\n"
        self.assertEqual(strip(body), "Intro\n\n## Next\n- [ ] item\n- [x] done\n")

    def test_rule_with_text_between_is_kept(self):
        body = "Intro\n\n---\n\nOutro\n\n" + FOOTER
        self.assertEqual(strip(body), "Intro\n\n---\n\nOutro")

    def test_only_footer_leaves_empty_body(self):
        self.assertEqual(strip(FOOTER), "")

    def test_similar_prose_is_not_a_footer(self):
        body = "This was generated with Claude Code and then edited by hand."
        self.assertIs(strip(body), body)


class Idempotence(unittest.TestCase):
    def test_second_pass_is_a_no_op(self):
        once = strip("Adds X.\n\n" + DOUBLED_FOOTER)
        self.assertIs(strip(once), once)


class CommandLine(unittest.TestCase):
    def test_stdin_to_stdout_utf8(self):
        body = ("Adds X.\n\n" + FOOTER).encode("utf-8")
        result = subprocess.run(
            [sys.executable, SCRIPT], input=body, capture_output=True, check=True
        )
        self.assertEqual(result.stdout.decode("utf-8"), "Adds X.")

    def test_unchanged_body_round_trips_byte_for_byte(self):
        body = BODY.encode("utf-8")
        result = subprocess.run(
            [sys.executable, SCRIPT], input=body, capture_output=True, check=True
        )
        self.assertEqual(result.stdout, body)


if __name__ == "__main__":
    unittest.main()
