#!/usr/bin/env python3
# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""Strip Claude Code attribution footers from a pull-request body.

Used by the `footer-cleanup` job in universal-semantic.yml, which runs on
every RokctAI pull request before `checklist-check`. Reads the PR body on
stdin and writes the cleaned body on stdout; the workflow diffs the two and
only PATCHes the PR when something was actually removed.

What is removed (case-insensitive, each on its own line, with or without a
markdown link, with or without `*`/`_` emphasis):

  🤖 Generated with [Claude Code](https://claude.com/claude-code)
  🤖 Generated with Claude Code
  https://claude.ai/code/session_<id>              (any session id)
  _Generated by [Claude Code](https://claude.ai/code)_
  Generated by Claude Code

plus a `---` horizontal rule that immediately precedes such a block and the
blank lines the block leaves behind. Nothing else in the body is touched
(checkboxes, headings, links, other rules). The function is idempotent and
returns the input object unchanged when nothing matches.

Run:  python3 scripts/pr_footer_cleanup.py < body.md > cleaned.md
Test: python3 scripts/tests/test_pr_footer_cleanup.py
"""

import re
import sys

# `[Claude Code](any url)` or the bare product name.
_CLAUDE_CODE = r"(?:\[Claude Code\]\([^)]*\)|Claude Code)"
# Optional markdown emphasis wrappers around a whole line: `_x_`, `*x*`, `**x**`.
_EMPH = r"[*_]{0,2}"

ATTRIBUTION_PATTERNS = [
    # 🤖 Generated with [Claude Code](https://claude.com/claude-code)
    re.compile(
        r"^"
        + _EMPH
        + r"(?:\U0001F916\s*)?Generated with "
        + _CLAUDE_CODE
        + r"\.?"
        + _EMPH
        + r"$",
        re.IGNORECASE,
    ),
    # _Generated by [Claude Code](https://claude.ai/code)_
    re.compile(
        r"^" + _EMPH + r"Generated by " + _CLAUDE_CODE + r"\.?" + _EMPH + r"$",
        re.IGNORECASE,
    ),
    # https://claude.ai/code/session_<id>, bare, <autolink>, or [text](url)
    re.compile(
        r"^" + _EMPH + r"(?:Session:\s*)?"
        r"(?:<https://claude\.ai/code/session_[A-Za-z0-9_-]+>"
        r"|\[[^\]]*\]\(https://claude\.ai/code/session_[A-Za-z0-9_-]+\)"
        r"|https://claude\.ai/code/session_[A-Za-z0-9_-]+)" + _EMPH + r"$",
        re.IGNORECASE,
    ),
]

_RULE = re.compile(r"^(?:-{3,}|\*{3,}|_{3,})$")


def is_attribution_line(line):
    """True when `line` (ignoring surrounding whitespace) is an attribution line."""
    text = line.strip()
    return any(p.match(text) for p in ATTRIBUTION_PATTERNS)


def _is_blank(line):
    return line.strip() == ""


def _mark_preceding_rules(lines, remove):
    """Also drop a `---` rule that sits directly above a removed block.

    Blank lines between the rule and the block are dropped with it. A rule
    that has ordinary text between it and the block is left alone.
    """
    for i, flagged in enumerate(remove):
        if not flagged or (i > 0 and remove[i - 1]):
            continue  # not the start of a removed run
        j = i - 1
        while j >= 0 and _is_blank(lines[j]):
            j -= 1
        if j >= 0 and _RULE.match(lines[j].strip()):
            for k in range(j, i):
                remove[k] = True


def strip_attribution(body):
    """Return `body` with attribution footers removed; unchanged input if none."""
    if not body:
        return body
    eol = "\r\n" if "\r\n" in body else "\n"
    lines = body.replace("\r\n", "\n").split("\n")
    remove = [is_attribution_line(line) for line in lines]
    if not any(remove):
        return body
    _mark_preceding_rules(lines, remove)

    out = []
    seam = False  # True while we are just past a removed block
    for line, flagged in zip(lines, remove):
        if flagged:
            seam = True
            continue
        if seam and _is_blank(line) and (not out or _is_blank(out[-1])):
            continue  # collapse the blank lines the block left behind
        seam = False
        out.append(line)
    if seam:  # the last removed block ran to the end of the body
        while out and _is_blank(out[-1]):
            out.pop()
    return eol.join(out)


def main():
    body = sys.stdin.buffer.read().decode("utf-8")
    sys.stdout.buffer.write(strip_attribution(body).encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
