name: Auto Assign

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions: write-all
on:
  pull_request:
    types: [opened]

jobs:
  assign:
    uses: RokctAI/shared-workflows/.github/workflows/universal-assign.yml@fed18a76a3107bcd8293a24d3e949addfdd09e84 # main
    secrets: inherit
