name: Auto Merge

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions: write-all
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    uses: RokctAI/shared-workflows/.github/workflows/universal-merge.yml@fed18a76a3107bcd8293a24d3e949addfdd09e84 # main
    with:
      allowed_users: "Rendani Sinyage, RendaniSinyage, RokctBOT, RokctBOT[bot]"
    secrets: inherit
