name: Universal Link Checker

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  PIP_BREAK_SYSTEM_PACKAGES: 1

permissions:
  contents: read
on:
  workflow_call:
    secrets:
      COUNTER_API_KEY:
        required: false

jobs:
  telemetry:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Track Usage
        env:
          API_KEY: ${{ secrets.COUNTER_API_KEY }}
        if: env.API_KEY != ''
        run: |
          curl -X GET "https://api.counterapi.dev/v2/rokctai/usage/up" \
          -H "Authorization: Bearer $API_KEY"

  link-check:
    needs: telemetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Link Checker
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # v1
        with:
          args: --verbose --no-progress './**/*.md'
          fail: false # Don't break build, just warn
