name: Universal PR Size Labeler

on:
  workflow_call:
    secrets:
      COUNTER_API_KEY:
        required: false

jobs:
  telemetry:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Track Usage
        env:
          API_KEY: ${{ secrets.COUNTER_API_KEY }}
        if: env.API_KEY != ''
        run: |
          curl -X GET "https://api.counterapi.dev/v2/rokctai/usage/up" \
          -H "Authorization: Bearer $API_KEY"

  size-label:
    needs: telemetry
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_lines: '10'
          s_label: 'size/s'
          s_max_lines: '100'
          m_label: 'size/m'
          m_max_lines: '500'
          l_label: 'size/l'
          l_max_lines: '1000'
          xl_label: 'size/xl'
          fail_if_xl: 'false'
