name: Universal License Eye

on:
  workflow_call:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check License Headers
        uses: apache/skywalking-eyes/header@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: check
          config: |
            header:
              license:
                spdx-id: MIT
                content: |
                  Copyright 2024 RokctAI
            paths:
              - '**/*.py'
              - '**/*.js'
              - '**/*.ts'
              - '**/*.dart'
            paths-ignore:
              - '**/*.json'
              - '**/*.md'
              - '**/*.yml'
              - '**/dist/**'
              - '**/node_modules/**'
