name: Welcome Bot

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions: write-all
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    uses: RokctAI/shared-workflows/.github/workflows/universal-welcome.yml@fed18a76a3107bcd8293a24d3e949addfdd09e84 # main
    secrets: inherit
